extends SceneTree
const Rules = preload("res://scripts/battle_model.gd")
const Planner = preload("res://scripts/enemy_planner.gd")

func _initialize() -> void:
	var model = Rules.new()
	model.reset()
	model.enemies.clear()
	model.player.cell = Vector2i(2,4)
	var heavy: Dictionary = model.make_enemy("heavy",Vector2i(2,2),0)
	model.enemies.append(heavy)
	var planner = Planner.new()
	assert(model.targets().has(Vector2i(2,3)))
	planner.begin(model)
	planner.beat(model,0)
	assert(heavy.cell == Vector2i(2,3) and heavy.ap == 0)
	planner.begin(model)
	var hp: int = model.player.hp
	planner.beat(model,0)
	assert(model.player.hp == hp-1 and heavy.cell == Vector2i(2,3))
	heavy.cell = Vector2i(2,2)
	model.mines.append(Vector2i(2,3))
	planner.begin(model)
	planner.beat(model,0)
	assert(heavy.cell == Vector2i(2,3) and heavy.hp == 1)
	heavy.cell = Vector2i(2,2)
	model.obstacles.assign([Vector2i(2,3),Vector2i(1,2),Vector2i(3,2)])
	planner.begin(model)
	planner.beat(model,0)
	assert(heavy.cell == Vector2i(2,1))
	model.obstacles.append(Vector2i(2,0))
	model.obstacles.append(Vector2i(1,1))
	model.obstacles.append(Vector2i(3,1))
	planner.begin(model)
	planner.beat(model,0)
	assert(heavy.cell == Vector2i(2,2))
	planner.begin(model)
	planner.beat(model,0)
	assert(heavy.cell == Vector2i(2,2) and heavy.ap == 0)
	print("Heavy AI: danger ignored, adjacent attack, mine entry, detour, blocked wait passed")
	quit()
